### ISSUE TITLE
Parallel limit

### ISSUE THREAD

**Issue by chackoge** [illinois-or-research-analytics/cm_pipeline#24]
In pipeline.json 

{
            "name": "clustering",
            "parallel_limit": 2
        },

seems to spawn 5 parallel clustering jobs one for each resolution in "resolution": [0.5, 0.1, 0.01, 0.001, 0.0001], I don't have an MWE handy sorry. It should be easy enough to test on a small network. Setting parallel_limit to 1 results in sequential behavior

**Comment by vikramr2** [comment]
Applied the fix to this issue

**Comment by vikramr2** [comment]
Now parallel limits will actually be enforced
