### ISSUE TITLE
k key missing in JSON Input Documentation

### ISSUE THREAD

**Issue by MinhyukPark** [illinois-or-research-analytics/cm_pipeline#29]
## Summary
It seems that the description for the k parameter key used in https://github.com/illinois-or-research-analytics/cm_pipeline/blob/2a9ff9071a97b8f0960991ec2994e3572746509d/source/workflow.py#L30 got dropped in the JSON Input Documentation.

Seemingly, the correct usage in the JSON file is
```
"k": INTEGER
```

**Comment by vikramr2** [comment]
Updated json_format.md
