### ISSUE TITLE
Running workflow.py with IKC results in an incorrectly named output file for IKC

### ISSUE THREAD

**Issue by MinhyukPark** [illinois-or-research-analytics/cm_pipeline#31]
## Summary
IKC doesn't output a TSV but rather a CSV but the clustering stage by default uses the .tsv suffix for the output file.

This doesn't matter in the end since it will get filtered by format_ikc_output.py anyways but the point still stands that it is a misleading filename.

**Comment by vikramr2** [comment]
Good point, but since this doesn't affect correctness, this is a backlog item

**Comment by vikramr2** [comment]
Rebuilt the pipeline to automatically convert to tsv

Moreover, I standardized clusterers to output tsvs for better standardization. That way users can introduce new clustering methods much easier.

Resolving for now.
