### ISSUE TITLE
Minor UIUC EngrIT systems requirement inadequecies

### ISSUE THREAD

**Issue by MinhyukPark** [illinois-or-research-analytics/cm_pipeline#32]
## Summary
There are a few things missing for the UIUC EngrIT systems requirements that could also affect other cluster users.

1. openmpi 4.0.1 depends on gcc 9.2.0, and the order of the loading would matter if the user has gcc 8 already loaded on the system. In those cases, one would have to module swap the gcc 8 with gcc 9 or the order of the commands should be swapped at least.
2. although python3 is loaded here, in a system as such, python2 would usually be the default symlink for the command `python`. In those cases, the workflow file that generates commands starting with `python` should be swapped with `python3` explicitly since CM codebase in incompatible with python2.

**Comment by vikramr2** [comment]
Good note! I switched the commands in the readme and switched all generated `python` commands to use `python3` instead
