### ISSUE TITLE
Checking input to cm.py

### ISSUE THREAD

**Issue by chackoge** [illinois-or-research-analytics/cm_pipeline#35]
I think it would be helpful if the input to cm.py (post-filtering) was checked for whether the tsv file contained no rows. The script should print a message and halt.

**Comment by ytabatabaee** [comment]
same thing should probably be done before the analysis step: if the output of cm+filtering was an empty clustering, the script should halt (rather than producing error)

**Comment by vikramr2** [comment]
Added extra checks to halt the pipeline on an error. CM also will just output an empty clustering if given an empty clustering. Error messages are more informative too

```
*** Starting filtering STAGE ***
Currently on resolution 0.5, running 2 iterations
[1] "OK 3 params supplied"
[1] "OK 3 params supplied"
Stage 2 Time Elapsed: 00:00:00
*** DONE ***
*** Starting connectivity_modifier STAGE ***
Currently on resolution 0.5, running 2 iterations
Stage 3 Time Elapsed: 00:00:02
*** DONE ***
*** Starting filtering STAGE ***
Currently on resolution 0.5, running 2 iterations
[1] "OK 2 params supplied"
Error: Error: Clustering is empty.
Execution halted
res-0.5-i2/S4_cit_hepph_lfr_leiden.0.5_i2_post_cm_filter.R.tsv failed to generate
```

Marking this as resolved
