### ISSUE TITLE
JSON documentation needs to be clearly advertised

### ISSUE THREAD

**Issue by alfredjynx** [illinois-or-research-analytics/cm_pipeline#40]
I would put the JSON documentation in the main README.md, since it is of extreme importance to the usage of the pipeline. Also, linking it in the Setup and Running Instructions would help out a lot. The documentation is really hidden, only accessible by one link on the front-page, which only becomes clear when the user has either already scrolled to the bottom of the page to get to the running instructions and is looking for more information or has tried and failed to run the code.

**Comment by vikramr2** [comment]
I have shortened the documentation to make it easier to find other documentation, lmk what you think.
