### ISSUE TITLE
Suggest dropping the S1 -> S2 stage

### ISSUE THREAD

**Issue by chackoge** [illinois-or-research-analytics/cm_pipeline#41]
To simplify the pipeline, an option is to skip the cleanup script and require users to clean their own edgelists and present them as header-free tsvs with integer_ids. You could run a check on the first 100 rows and return an error if the input edgelist fails the check. If it passes, just rename the file S2....

**Comment by vikramr2** [comment]
Cleanup is no longer a hard requirement in the pipeline. Marking this as resolved!
